const FAST_FOOD_CHAINS_US_SEED = [
  "7 Brew Coffee",
  "A&W Restaurants",
  "Arthur Treacher's Fish & Chips",
  "Au Bon Pain",
  "Auntie Anne's",
  "Back Yard Burgers",
  "Baja Fresh",
  "Baskin-Robbins",
  "bb.q Chicken",
  "Bibibop Asian Grill",
  "Biggby Coffee",
  "Black Rock Coffee Bar",
  "Blaze Pizza",
  "Blimpie",
  "Bojangles",
  "Bonchon",
  "Braum's",
  "Bruegger's Bagels",
  "Buffalo Wild Wings",
  "Burger Fi",
  "Burger King",
  "BurgerIM",
  "Cafe Rio",
  "California Pizza Kitchen",
  "Capriotti's",
  "Captain D's",
  "Carl's Jr.",
  "Charleys Philly Steaks",
  "Checkers",
  "Cheba Hut",
  "Chester's Chicken",
  "Chick-fil-A",
  "Chipotle",
  "Chopt",
  "Chronic Tacos",
  "Church's Texas Chicken",
  "Cicis",
  "Cinnabon",
  "Cold Stone Creamery",
  "Cook Out",
  "Costa Vida",
  "Cousins Subs",
  "Crumbl Cookies",
  "Culver's",
  "Dairy Queen",
  "Dave's Hot Chicken",
  "Del Taco",
  "Dickey's Barbecue Pit",
  "Dippin' Dots",
  "Domino's",
  "Donatos Pizza",
  "Duck Donuts",
  "Dutch Bros Coffee",
  "Dunkin'",
  "East Coast Wings + Grill",
  "Einstein Bros. Bagels",
  "El Pollo Loco",
  "Erbert and Gerbert's",
  "Fatburger",
  "Fazoli's",
  "Firehouse Subs",
  "Five Guys",
  "Foosackly's",
  "Freddy's Frozen Custard & Steakburgers",
  "Freshii",
  "Freebirds World Burrito",
  "Fuddruckers",
  "Fuzzy's Taco Shop",
  "Garbanzo Mediterranean Fresh",
  "Godfather's Pizza",
  "Golden Chick",
  "Great American Cookies",
  "Hardee's",
  "In-N-Out Burger",
  "Insomnia Cookies",
  "Jack in the Box",
  "Jamba",
  "Jason's Deli",
  "Jeremiah's Italian Ice",
  "Jersey Mike's",
  "Jollibee",
  "KFC",
  "Kona Ice",
  "Krispy Krunchy Chicken",
  "Krispy Kreme",
  "LaMar's Donuts",
  "Lee's Famous Recipe Chicken",
  "Ledo Pizza",
  "Little Caesars",
  "Long John Silver's",
  "Marco's Pizza",
  "Mazzio's Pizza",
  "McAlister's Deli",
  "McDonald's",
  "Menchie's",
  "Mighty Taco",
  "Mission BBQ",
  "MOD Pizza",
  "Moe's Southwest Grill",
  "Mountain Mike's Pizza",
  "Naf Naf Grill",
  "Nando's",
  "Nathan's Famous",
  "Noodles & Company",
  "Noah's New York Bagels",
  "Orange Julius",
  "Panda Express",
  "Panera Bread",
  "Papa John's",
  "Papa Murphy's",
  "Papa Gino's",
  "Pancheros",
  "PDQ",
  "Peet's Coffee",
  "Pei Wei",
  "Penn Station East Coast Subs",
  "Peter Piper Pizza",
  "Pita Pit",
  "Pick Up Stix",
  "Pinkberry",
  "Pizza Hut",
  "Pizza Patrón",
  "Pizza Ranch",
  "Planet Smoothie",
  "Pollo Campero",
  "Pollo Tropical",
  "Pokeworks",
  "Popeyes",
  "Port of Subs",
  "Portillo's",
  "Potbelly",
  "Pret A Manger",
  "Pretzelmaker",
  "PrimoHoagies",
  "Qdoba",
  "Quiznos",
  "Raising Cane's",
  "Rally's",
  "Rita's Italian Ice",
  "Robeks",
  "Rosati's Pizza",
  "Round Table Pizza",
  "Salsarita's Fresh Mexican Grill",
  "Saladworks",
  "Sarku Japan",
  "Sbarro",
  "Schlotzsky's",
  "Scooter's Coffee",
  "Shake Shack",
  "Shipley Do-Nuts",
  "Slim Chickens",
  "Smashburger",
  "Smoothie King",
  "Sonic Drive-In",
  "Starbucks",
  "Steak 'n Shake",
  "Subway",
  "Sweet Frog",
  "Sweetgreen",
  "Taco Bell",
  "Taco Bueno",
  "Taco Cabana",
  "Taco Casa",
  "Taco John's",
  "Taco Mayo",
  "Taco Tico",
  "Taco Time",
  "TCBY",
  "Teriyaki Madness",
  "The Coffee Bean & Tea Leaf",
  "The Habit Burger Grill",
  "The Halal Guys",
  "Tim Hortons",
  "Tijuana Flats",
  "Togo's",
  "Toppers Pizza",
  "Torchy's Tacos",
  "Tropical Smoothie Cafe",
  "Tubby's Sub Shops",
  "Wahlburgers",
  "Wayback Burgers",
  "Wendy's",
  "Wetzel's Pretzels",
  "Whataburger",
  "Which Wich",
  "White Castle",
  "Wienerschnitzel",
  "Wing Zone",
  "Wingstop",
  "WingStreet",
  "Yogurtland",
  "Yoshinoya",
  "Zankou Chicken",
  "Zaxby's",
  "Zoës Kitchen",
];

// Keep aliases *targeted*—too many creates false positives.
// These are mostly punctuation/spacing/renames/known “what people type” variants.
const FAST_FOOD_CHAIN_ALIASES = {
  "7 Brew Coffee": ["7brew", "seven brew", "7 brew"],
  "A&W Restaurants": ["a&w", "a & w", "a and w"],
  "Arthur Treacher's Fish & Chips": ["arthur treachers", "arthur treacher fish and chips"],
  "Au Bon Pain": ["aubonpain"],
  "Auntie Anne's": ["auntie annes", "auntie anne"],
  "Baskin-Robbins": ["baskin robbins", "baskinrobbins"],
  "bb.q Chicken": ["bbq chicken", "bb q chicken", "bbqchicken"],
  "Biggby Coffee": ["biggby", "bigby coffee"],
  "Burger Fi": ["burgerfi"],
  "Cafe Rio": ["café rio", "caferio"],
  "Capriotti's": ["capriottis", "capriotti"],
  "Captain D's": ["captain ds", "captain d’s"],
  "Carl's Jr.": ["carls jr", "carl's junior", "carls junior"],
  "Charleys Philly Steaks": ["charley's philly steaks", "charleys", "charley's"],
  "Chester's Chicken": ["chesters chicken", "chester chicken"],
  "Chick-fil-A": ["chickfila", "chick fil a", "chick-fil-a"],
  "Church's Texas Chicken": ["church's chicken", "churchs chicken"],
  "Cicis": ["cici's", "cici's pizza", "cicis pizza"],
  "Culver's": ["culvers"],
  "Dave's Hot Chicken": ["daves hot chicken", "dave s hot chicken"],
  "Dickey's Barbecue Pit": ["dickey's bbq", "dickey's barbecue", "dickey's bbq pit", "dickeys bbq"],
  "Domino's": ["dominos", "domino's pizza", "dominos pizza"],
  "Dunkin'": ["dunkin", "dunkin donuts", "dunkin' donuts"],
  "Einstein Bros. Bagels": ["einstein bros bagels", "einstein bagels"],
  "Erbert and Gerbert's": ["erbert & gerbert's", "erbert and gerberts", "erbert & gerberts"],
  "Foosackly's": ["foosacklys"],
  "Freddy's Frozen Custard & Steakburgers": ["freddys", "freddy's", "freddy's steakburgers"],
  "Godfather's Pizza": ["godfathers pizza", "godfather pizza"],
  "Hardee's": ["hardees"],
  "In-N-Out Burger": ["in n out", "in-n-out", "innout"],
  "Jack in the Box": ["jack-in-the-box", "jackinthebox"],
  "Jamba": ["jamba juice"],
  "Jersey Mike's": ["jersey mikes", "jersey mike's subs"],
  "KFC": ["kentucky fried chicken", "k f c"],
  "Krispy Kreme": ["krispykreme"],
  "LaMar's Donuts": ["lamars donuts", "lamar's donuts", "lamar donuts"],
  "Lee's Famous Recipe Chicken": ["lees famous recipe chicken", "lee's chicken", "lees chicken"],
  "Marco's Pizza": ["marcos pizza"],
  "McAlister's Deli": ["mcalisters deli", "mcalister's"],
  "McDonald's": ["mcdonalds", "mc donalds", "mc'donalds"],
  "Nando's": ["nandos"],
  "Noah's New York Bagels": ["noahs new york bagels", "noah's bagels", "noahs bagels"],
  "Panera Bread": ["panera", "panera bakery cafe", "panera bread co"],
  "Papa John's": ["papa johns", "papa john's pizza"],
  "Papa Murphy's": ["papa murphys", "papa murphy's take n bake", "papa murphy's take 'n' bake"],
  "Papa Gino's": ["papa ginos"],
  "Pei Wei": ["peiwei"],
  "Pizza Hut": ["pizza hut express"],
  "Popeyes": ["popeyes chicken", "popeyes louisiana kitchen"],
  "Portillo's": ["portillos"],
  "Pret A Manger": ["pret a manger", "pret-a-manger"],
  "Qdoba": ["qdoba mexican eats", "qdo ba", "q-doba"],
  "Raising Cane's": ["raising canes", "raising cane's chicken fingers"],
  "Rally's": ["rallys"],
  "Rita's Italian Ice": ["ritas italian ice", "rita's ice"],
  "Schlotzsky's": ["schlotzskys", "schlotzsky"],
  "Shipley Do-Nuts": ["shipley donuts", "shipley's donuts", "shipleys donuts"],
  "Steak 'n Shake": ["steak n shake", "steak and shake", "steak 'n shake"],
  "Taco Bell": ["tacobell"],
  "Wendy's": ["wendys"],
  "Wienerschnitzel": ["der wienerschnitzel"],
  "Wingstop": ["wing stop"],
  "Zaxby's": ["zaxbys"],
  "Zoës Kitchen": ["zoe's kitchen", "zoes kitchen"]
};

module.exports = FAST_FOOD_CHAINS_US_SEED;
module.exports.ALIASES = FAST_FOOD_CHAIN_ALIASES;
module.exports.CHAINS = FAST_FOOD_CHAINS_US_SEED;
